name: Java CI with Gradle

on:
  push:
    branches: [ "aa2526" ]
  pull_request:
    branches: [ "aa2526" ]

permissions:
  contents: write
  checks: write
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: 'always'
          dependency-graph: generate-and-submit
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: "yes"
      - name: Build with Gradle
        run: ./gradlew -PdoPMD=1 -PdoCheckstyle=1 build --scan
      - name: Test Reports
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Jubbiot Tests
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit   
      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: build/reports/